### PR TITLE
example updates

### PR DESCRIPTION
**Pull request by danomatika**
Another set of example-related updates:
- removed example project files
- added info on how to use the PG
- updated examples & addon for new OF (deprecations, etc)

### CODE REVIEW

**Comment by danomatika** [comment]
ping

**Comment by danomatika** [comment]
pinging again, the updates in the PR are tested...

**Comment by kylemcdonald** [comment]
Sorry for the delay Dan. Thanks so much for keeping this up to date, I find myself needing this addon when I least expect it and it's good to know someone with experience is putting some love into it since last time I used it :)

**Comment by danomatika** [comment]
:)

**Pull request merged**
